### PR TITLE
Add in support got GoogleTagManager with injected ID

### PR DESCRIPTION
**Pull request by scottaubrey**
related https://github.com/elifesciences/enhanced-preprints-client/issues/104

### CODE REVIEW

**Review by will-byrne — APPROVED** [review]

**Comment by discodavey** [comment]
Has the ID for the journal been added as this does not need it's own reporting as it can be done as part of the main journal.

**Comment by scottaubrey** [comment]
> Has the ID for the journal been added as this does not need it's own reporting as it can be done as part of the main journal.
> 

I believe so, see https://github.com/elifesciences/enhanced-preprints-client/issues/104

**Comment by scottaubrey** [comment]
Though again we will need to make and consider what an EPP for biophysics looks like - I'm not sure we want analytics mixed with our own

**Comment by scottaubrey** [comment]
> Paul said last week that we did not need to set up another account for it. Best speak to him

Yeah, for launch that's definitely true. For eLife ongoing that's almost definitely still true. If I had thought otherwise, I would have objected at the time.

I'm was just saying, like other things we've done in EPP for eLife - this might need reconsidering for biophysics.

**Pull request merged**
