### PR TITLE
Adds timeline events for more launch examples

### PR DESCRIPTION
**Pull request by FAtherden-eLife**
- Adds timeline information for next set of reviewed preprints
- Revised status description inline with Chris' latest designs
- Timeline event name changed from `Peer review` to `Sent for peer review`

### CODE REVIEW

**Review by scottaubrey — DISMISSED** [review]
Thanks Fred, this is great.

RE: the new manuscripts - I haven't yet had time to cross-reference the spreadsheet with [what we have already imported](https://github.com/elifesciences/enhanced-preprints-data/tree/master/data/10.1101) and add/remove the XMLs. I'm pretty sure we don't have them all imported yet though, and until they are, we'd only cause errors in EPP client by enabling them, so there is some dependancies before we can merge this.

When when we have imported them though, this looks good to me, and supersedes the PR [here](https://github.com/elifesciences/enhanced-preprints-client/pull/96)

**Review by scottaubrey — DISMISSED** [review]

**Comment by scottaubrey** [comment]
@FAtherden-eLife - I've resolved some conflicts with master branch, mostly around us both importing a new article. You might want to give it a quick glance, and feel free to merge when you're ready.

**Comment by FAtherden-eLife** [comment]
Thanks for that @scottaubrey - I made one small change, but think otherwise OK from my perspective.

**Review by scottaubrey — COMMENTED** [review]
@FAtherden-eLife what's the reason for removing this one? This is the one I was working towards getting up and running.

**Comment by FAtherden-eLife** [comment]
Sorry, just a misunderstanding. 

Based on your [comment above](https://github.com/elifesciences/enhanced-preprints-client/pull/112#pullrequestreview-1137587109), the data [currently available](https://github.com/elifesciences/enhanced-preprints-data/tree/master/data/10.1101), and your [previous commit](https://github.com/elifesciences/enhanced-preprints-client/pull/112/commits/cd908bcbbc76a6451ba5c86f50be02d81509cda5) (which I glanced at and based on the diff in that link looked to me like it was removed, but I see now it wasn't?), I had assumed that including it would cause issues. 

I'll add it back in now.

**Review by scottaubrey — APPROVED** [review]

**Comment by scottaubrey** [comment]
Changes should appear in about 20 mins

**Comment by FAtherden-eLife** [comment]
Thanks!

**Pull request merged**
