### PR TITLE
Clipboard positioning fix

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by discodavey** [comment]
@chris-huggins Another one for you to review

**Comment by chris-huggins** [comment]
@discodavey I'm getting 500 error when trying to open an article on https://pr-357--epp.elifesciences.org/

**Comment by discodavey** [comment]
I'll update the branch and see if this fixes it @chris-huggins

**Comment by discodavey** [comment]
@scottaubrey Getting a 500 server error on this. Please can you investigate.

**Review by scottaubrey — APPROVED** [review]

**Pull request merged**
