### PR TITLE
remove space that's not needed

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Review by viktoria-mahmud — APPROVED** [review]

**Comment by discodavey** [comment]
@chris-huggins When the preview is available can you please just check all is ok. It was only a stray space causing the issue.

**Comment by elife-alfred-user** [comment]
## Preview environment images deployed!

The preview environment has been updated:
client image tag: preview-1077-48c4f37bb8b9f509735b1cbeb710d15a769ad798-20230823.0745
storybook image tag: preview-1077-48c4f37bb8b9f509735b1cbeb710d15a769ad798-20230823.0745

Client URL: https://pr-1077--epp.elifesciences.org
Storybook URL: https://pr-1077--epp-storybook.elifesciences.org

**Note**: Updated images can take a few minutes to roll out.

**Comment by elife-alfred-user** [comment]
## Preview environment created!

The preview environment has been deployed to the cluster.

Client URL: https://pr-1077--epp.elifesciences.org
Storybook URL: https://pr-1077--epp-storybook.elifesciences.org

**Note**: If this is a new environment, it can take a few minutes for DNS to update.

**Comment by chris-huggins** [comment]
Thanks for this @discodavey and @viktoria-mahmud. The commas and spaces looks great. However, I'm not sure if it's just this example article but the year appears to be missing after the author names. Could this be to do with this PR? I can see the year in Storybook so not sure if it's something else?

85111 from PR:

image

85111 In Production:

image

Cite modal in storybook:
image


And so you know, some of the font sizes are smaller than they should/than on journal so I'll raise a separate ticket for those as it seems to have been the case before this PR but I must have missed it.

**Pull request merged**
