### PR TITLE
Fix tabbed navigation full width

### PR DESCRIPTION
**Pull request by viktoria-mahmud**

### CODE REVIEW

**Comment by elife-alfred-user** [comment]
## Preview environment created!

The preview environment has been deployed to the cluster.

Client URL: https://pr-1102--epp.elifesciences.org
Storybook URL: https://pr-1102--epp-storybook.elifesciences.org

**Note**: If this is a new environment, it can take a few minutes for DNS to update.

**Comment by elife-alfred-user** [comment]
## Preview environment images deployed!

The preview environment has been updated:
client image tag: preview-1102-bea1a028813c44ee5967bc0d469ba721495e66de-20230901.0904
storybook image tag: preview-1102-bea1a028813c44ee5967bc0d469ba721495e66de-20230901.0904

Client URL: https://pr-1102--epp.elifesciences.org
Storybook URL: https://pr-1102--epp-storybook.elifesciences.org

**Note**: Updated images can take a few minutes to roll out.

**Review by discodavey — APPROVED** [review]
Tested this and looks good. Just double check previous commit history to see what was done.

**Comment by viktoria-mahmud** [comment]
The changes were related to the text in the tabs on small screens but dispaly values were changed too. I noticed that there are tab texts on two rows when the screen size is around 320px and above, so I added additional style.

> Tested this and looks good. Just double check previous commit history to see what was done.

**Pull request merged**
