### PR TITLE
Change order in timeline

### PR DESCRIPTION
**Pull request by viktoria-mahmud**

### CODE REVIEW

**Review by FAtherden-eLife — APPROVED** [review]

**Comment by nlisgo** [comment]
@FAtherden-eLife we have created a ticket so that even if the manuscript.json has a timeline in the incorrect order we can display it in the correct order. This should avoid this concern in future.

Thanks for your patience

**Comment by nlisgo** [comment]
Here is the ticket: https://github.com/elifesciences/enhanced-preprints-issues/issues/458

**Comment by FAtherden-eLife** [comment]
Great - thanks Nathan!

**Comment by nlisgo** [comment]
@FAtherden-eLife this should be fixed now: https://elifesciences.org/reviewed-preprints/84628

**Comment by FAtherden-eLife** [comment]
Looks good - thanks!

**Pull request merged**
