### PR TITLE
Pass id through for reviews

### PR DESCRIPTION
**Pull request by nlisgo**
This can be considered for review after the following PR has been deployed to production: https://github.com/elifesciences/enhanced-preprints-server/pull/690

### CODE REVIEW

**Comment by nlisgo** [comment]
Now the corresponding server PR has been merged in I will mark this ready for review once the server code has been deployed to production.

**Review by scottaubrey — APPROVED** [review]
This looks good, nice and simple. 

I've not run the code, but the preview env works as expected against staging API, so I'm happy to go with this. 👍

**Comment by scottaubrey** [comment]
> This looks good, nice and simple.
> 
> I've not run the code, but the preview env works as expected against staging API, so I'm happy to go with this. 👍

@nlisgo One final thing - the reviews.json override in the cluster also needs to be undone too I assume?

**Comment by nlisgo** [comment]
> @nlisgo One final thing - the reviews.json override in the cluster also needs to be undone too I assume?

The plan would be to deploy this change and then when it's in production demonstrate that removing the reviews for 85111 will result in no change, then remove it.

**Pull request merged**
