### PR TITLE
Change Twitter icon to new X Logo

### PR DESCRIPTION
**Pull request by discodavey**

### CODE REVIEW

**Comment by elife-alfred-user** [comment]
## Preview environment created!

The preview environment has been deployed to the cluster.

Client URL: https://pr-1779--epp.elifesciences.org
Storybook URL: https://pr-1779--epp-storybook.elifesciences.org

**Note**: If this is a new environment, it can take a few minutes for DNS to update.

**Comment by elife-alfred-user** [comment]
## Preview environment images deployed!

The preview environment has been updated:
client image tag: preview-1779-8b113c02094ae4fc3b2170d5bb1d305bd08d0a0d-20240319.1213
storybook image tag: preview-1779-8b113c02094ae4fc3b2170d5bb1d305bd08d0a0d-20240319.1213

Client URL: https://pr-1779--epp.elifesciences.org
Storybook URL: https://pr-1779--epp-storybook.elifesciences.org

**Note**: Updated images can take a few minutes to roll out.

**Comment by discodavey** [comment]
@chris-huggins Can you please look at the new logo's and say if you are happy with this?

https://pr-1779--epp.elifesciences.org/

**Comment by chris-huggins** [comment]
Looks good to me, thanks @discodavey

**Pull request merged**
