### PR TITLE
Display unconfirmed ORCID iD in author information list

### PR DESCRIPTION
**Pull request by nlisgo**
@chris-huggins your design does not cater for multiple ORCID's but the data structure supports it so I'm not sure how much attention we need to give this but I've decided to present the ORCID's in a single line comma separated if there are multiple. The alternative approach would be to just choose the first ORCID encountered.

Screenshot from 2022-12-20 09-54-00

Screenshot from 2022-12-20 09-54-34

I will provide links for you to confirm the appearance is as expected once the preview environment is available.

### CODE REVIEW

**Comment by nlisgo** [comment]
@chris-huggins 

https://pr-298--epp.elifesciences.org/reviewed-preprints/80984#author-list

**Comment by nlisgo** [comment]
Here you can see the example with multiple ORCID's in storybook:

https://pr-298--epp-storybook.elifesciences.org/?path=/story/molecules-authorinformationlist--authors

**Comment by chris-huggins** [comment]
Looks good to me, thanks @nlisgo.

**Review by scottaubrey — APPROVED** [review]

**Comment by nlisgo** [comment]
Thanks for the review @chris-huggins and @scottaubrey

**Pull request merged**
