### PR TITLE
add link to logo to homepage and remove unwanted padding

### PR DESCRIPTION
**Pull request by discodavey**
site-header__logo_link was not being used until I put in the link

### CODE REVIEW

**Comment by discodavey** [comment]
Here you go @chris-huggins. Link added as well as removing padding to the right.

**Comment by chris-huggins** [comment]
This looks good to me thanks @discodavey. I'm assuming the link that takes me to https://pr-373--epp.elifesciences.org/ on the PR would point to homepage in reality.

**Comment by chris-huggins** [comment]
This looks good to me thanks @discodavey. I'm assuming the link that takes me to https://pr-373--epp.elifesciences.org/ on the PR would point to homepage in reality.

**Comment by discodavey** [comment]
@chris-huggins I had a chat with @scottaubrey and confirmed it would go back to the eLife homepage

**Comment by chris-huggins** [comment]
@discodavey Ok all good with me then, thanks

**Review by scottaubrey — APPROVED** [review]

**Pull request merged**
